// examples/react-latest/src/CustomMenuButton.tsx
import { useEffect } from 'react'
import {
  CourierInboxPopupMenu,
  useCourier,
  type CourierInboxMenuButtonFactoryProps,
} from '@trycourier/courier-react';

const CustomMenuButton = ({ totalUnreadCount, feeds }: CourierInboxMenuButtonFactoryProps) => (
  <button>
    Open the Inbox Popup. Total unread count: {totalUnreadCount}
  </button>
);

export default function App() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
      showLogs: false,
    });
  }, []);

  return (
    <div style={{ padding: '24px' }}>
      <CourierInboxPopupMenu
        renderMenuButton={(props: CourierInboxMenuButtonFactoryProps | null | undefined) => {
          return <CustomMenuButton totalUnreadCount={props?.totalUnreadCount || 0} feeds={props?.feeds || []} />
        }}
      />
    </div>
  );

}

// examples/vue/src/CustomMenuButton.vue
<script setup lang="ts">
import { h, onMounted, type VNodeChild } from 'vue';
import {
  CourierInboxPopupMenu,
  useCourier,
  type CourierInboxMenuButtonFactoryProps,
} from '@trycourier/courier-vue';

const courier = useCourier();

onMounted(() => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
    showLogs: false,
  });
});

const renderMenuButton = (props: CourierInboxMenuButtonFactoryProps | null | undefined): VNodeChild => {
  const totalUnreadCount = props?.totalUnreadCount ?? 0;
  return h('button', `Open the Inbox Popup. Total unread count: ${totalUnreadCount}`);
};
</script>

<template>
  <div :style="{ padding: '24px' }">
    <CourierInboxPopupMenu :render-menu-button="renderMenuButton" />
  </div>
</template>
