// examples/react-17/src/CustomListItems.tsx
import { useEffect } from 'react'
import {
  CourierInbox,
  useCourier,
  type CourierInboxListItemFactoryProps,
} from '@trycourier/courier-react-17';

const CustomListItem = ({ message, index }: CourierInboxListItemFactoryProps) => (
  <pre style={{
    padding: '24px',
    borderBottom: '1px solid #e0e0e0',
    margin: '0'
  }}>
    {JSON.stringify({ message, index }, null, 2)}
  </pre>
);

export default function App() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
      showLogs: false,
    });
  }, []);

  return (
    <CourierInbox
      renderListItem={(props: CourierInboxListItemFactoryProps | null | undefined) => {
        if (!props) return <></>;
        return <CustomListItem {...props} />;
      }}
    />
  );

}

// examples/vue/src/CustomListItems.vue
<script setup lang="ts">
import { h, onMounted, type VNodeChild } from 'vue';
import {
  CourierInbox,
  useCourier,
  type CourierInboxListItemFactoryProps,
} from '@trycourier/courier-vue';

const courier = useCourier();

onMounted(() => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
    showLogs: false,
  });
});

const renderListItem = (props: CourierInboxListItemFactoryProps | null | undefined): VNodeChild => {
  if (!props) return null;
  const { message, index } = props;
  return h(
    'pre',
    {
      onClick: () => alert(JSON.stringify({ message, index }, null, 2)),
      style: {
        padding: '24px',
        borderBottom: '1px solid #e0e0e0',
        margin: '0',
      },
    },
    JSON.stringify({ message, index }, null, 2)
  );
};
</script>

<template>
  <CourierInbox :render-list-item="renderListItem" />
</template>
