// examples/next-latest/src/app/examples/inbox-custom-tabs/page.tsx
'use client'

import { useEffect } from 'react'
import {
  CourierInbox,
  useCourier,
  type CourierInboxFeed,
} from '@trycourier/courier-react'

export default function InboxCustomTabs() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: process.env.NEXT_PUBLIC_USER_ID!,
      jwt: process.env.NEXT_PUBLIC_JWT!,
    });
  }, []);

  // Single feed with multiple tabs for filtering
  const feeds: CourierInboxFeed[] = [
    {
      feedId: 'notifications',
      title: 'Notifications',
      tabs: [
        {
          datasetId: 'all-notifications',
          title: 'All',
          filter: {}
        },
        {
          datasetId: 'unread-notifications',
          title: 'Unread',
          filter: { status: 'unread' }
        },
        {
          datasetId: 'read-notifications',
          title: 'Read',
          filter: { status: 'read' }
        },
        {
          datasetId: 'important',
          title: 'Important',
          filter: { tags: ['important'] }
        },
        {
          datasetId: 'archived',
          title: 'Archived',
          filter: { archived: true }
        }
      ]
    }
  ];

  return (
    <div style={{ padding: '24px' }}>
      <CourierInbox feeds={feeds} />
    </div>
  );

}

// examples/vue/src/InboxCustomTabs.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { CourierInbox, useCourier, type CourierInboxFeed } from '@trycourier/courier-vue';

const courier = useCourier();

onMounted(() => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
  });
});

// Single feed with multiple tabs for filtering
const feeds: CourierInboxFeed[] = [
  {
    feedId: 'notifications',
    title: 'Notifications',
    tabs: [
      { datasetId: 'all-notifications', title: 'All', filter: {} },
      { datasetId: 'unread-notifications', title: 'Unread', filter: { status: 'unread' } },
      { datasetId: 'read-notifications', title: 'Read', filter: { status: 'read' } },
      { datasetId: 'important', title: 'Important', filter: { tags: ['important'] } },
      { datasetId: 'archived', title: 'Archived', filter: { archived: true } },
    ],
  },
];
</script>

<template>
  <div :style="{ padding: '24px' }">
    <CourierInbox :feeds="feeds" />
  </div>
</template>
