// examples/react-latest/src/InboxActions.tsx
import { useEffect } from 'react'
import {
  CourierInbox,
  useCourier,
  type CourierInboxListItemFactoryProps,
  type CourierInboxListItemActionFactoryProps,
} from '@trycourier/courier-react';

export default function App() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }, []);

  return (
    <div style={{ padding: '24px' }}>
      <CourierInbox
        onMessageClick={({ message, index }: CourierInboxListItemFactoryProps) => {
          alert("Message clicked at index " + index + ":\n" + JSON.stringify(message, null, 2));
        }}
        onMessageActionClick={({ message, action, index }: CourierInboxListItemActionFactoryProps) => {
          alert(
            "Message action clicked at index " + index + ":\n" +
            "Action: " + JSON.stringify(action, null, 2) + "\n" +
            "Message: " + JSON.stringify(message, null, 2)
          );
        }}
        onMessageLongPress={({ message, index }: CourierInboxListItemFactoryProps) => {
          alert("Message long pressed at index " + index + ":\n" + JSON.stringify(message, null, 2));
        }}
      />
    </div>
  );

}

// examples/vue/src/InboxActions.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import {
  CourierInbox,
  useCourier,
  type CourierInboxListItemFactoryProps,
  type CourierInboxListItemActionFactoryProps,
} from '@trycourier/courier-vue';

const courier = useCourier();

onMounted(() => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
  });
});

const handleMessageClick = ({ message, index }: CourierInboxListItemFactoryProps) => {
  alert('Message clicked at index ' + index + ':\n' + JSON.stringify(message, null, 2));
};

const handleMessageActionClick = ({ message, action, index }: CourierInboxListItemActionFactoryProps) => {
  alert(
    'Message action clicked at index ' + index + ':\n' +
    'Action: ' + JSON.stringify(action, null, 2) + '\n' +
    'Message: ' + JSON.stringify(message, null, 2)
  );
};

const handleMessageLongPress = ({ message, index }: CourierInboxListItemFactoryProps) => {
  alert('Message long pressed at index ' + index + ':\n' + JSON.stringify(message, null, 2));
};
</script>

<template>
  <div :style="{ padding: '24px' }">
    <CourierInbox
      :on-message-click="handleMessageClick"
      :on-message-action-click="handleMessageActionClick"
      :on-message-long-press="handleMessageLongPress"
    />
  </div>
</template>
