// examples/react-latest/src/MarkdownListItem.tsx
import { useEffect, useState } from 'react'
import { CourierInbox, useCourier, type CourierInboxListItemFactoryProps } from '@trycourier/courier-react'
import Markdown from 'markdown-to-jsx';

export default function MarkdownListItemInbox() {
  const [courierJwt, setCourierJwt] = useState<string>()
  const refreshCourierJwt = async () => {
    await new Promise((resolve, _) => window.setTimeout(resolve, 10));
    setCourierJwt(import.meta.env.VITE_JWT);
  };

  const courier = useCourier();

  useEffect(() => {
    refreshCourierJwt();
  }, []);

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: courierJwt,
    });
  }, [courierJwt]);

  return (
    <CourierInbox
      renderListItem={(props: CourierInboxListItemFactoryProps) => {
        return (
          <div>
            <Markdown>{props.message.preview || ""}</Markdown>
          </div>
        );
      }}
    />
  );
}

// examples/vue/src/MarkdownListItem.vue
<script setup lang="ts">
import { h, onMounted, ref, watch, type VNodeChild } from 'vue';
import { CourierInbox, useCourier, type CourierInboxListItemFactoryProps } from '@trycourier/courier-vue';
import { marked } from 'marked';

const courier = useCourier();
const courierJwt = ref<string | undefined>(undefined);

const refreshCourierJwt = async () => {
  await new Promise((resolve) => window.setTimeout(resolve, 10));
  courierJwt.value = import.meta.env.VITE_JWT;
};

onMounted(() => {
  refreshCourierJwt();
});

watch(courierJwt, (jwt) => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt,
  });
});

const renderListItem = (props: CourierInboxListItemFactoryProps | null | undefined): VNodeChild => {
  const html = marked.parse(props?.message?.preview ?? '', { async: false }) as string;
  return h('div', [h('div', { innerHTML: html })]);
};
</script>

<template>
  <CourierInbox :render-list-item="renderListItem" />
</template>
