// examples/angular/src/app/pages/markdown-list-item.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CourierInboxComponent, CourierService } from '@trycourier/courier-angular';
import { marked } from 'marked';

@Component({
  selector: 'app-markdown-list-item',
  standalone: true,
  imports: [CommonModule, CourierInboxComponent],
  template: `
    <courier-inbox>
      <ng-template #listItem let-props>
        <div>
          <div [innerHTML]="renderMarkdown(props?.message?.preview)"></div>
        </div>
      </ng-template>
    </courier-inbox>
  `,
})
export class MarkdownListItemComponent implements OnInit {
  constructor(private courier: CourierService) {}

  ngOnInit(): void {
    this.refreshCourierJwt();
  }

  private async refreshCourierJwt(): Promise<void> {
    await new Promise((resolve) => window.setTimeout(resolve, 10));
    this.courier.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }

  renderMarkdown(preview: string | undefined | null): string {
    return marked.parse(preview ?? '', { async: false }) as string;
  }
}

// examples/vue/src/MarkdownListItem.vue
<script setup lang="ts">
import { h, onMounted, ref, watch, type VNodeChild } from 'vue';
import { CourierInbox, useCourier, type CourierInboxListItemFactoryProps } from '@trycourier/courier-vue';
import { marked } from 'marked';

const courier = useCourier();
const courierJwt = ref<string | undefined>(undefined);

const refreshCourierJwt = async () => {
  await new Promise((resolve) => window.setTimeout(resolve, 10));
  courierJwt.value = import.meta.env.VITE_JWT;
};

onMounted(() => {
  refreshCourierJwt();
});

watch(courierJwt, (jwt) => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt,
  });
});

const renderListItem = (props: CourierInboxListItemFactoryProps | null | undefined): VNodeChild => {
  const html = marked.parse(props?.message?.preview ?? '', { async: false }) as string;
  return h('div', [h('div', { innerHTML: html })]);
};
</script>

<template>
  <CourierInbox :render-list-item="renderListItem" />
</template>
