// examples/vue-published/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { CourierInbox, useCourier } from '@trycourier/courier-vue';

// Grab the shared Courier instance provided by the SDK.
const courier = useCourier();

onMounted(() => {
  // Sign the user in so the inbox can load their messages. Without valid
  // credentials the inbox renders its empty / signed-out state.
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
  });
});
</script>

<template>
  <CourierInbox />
</template>

// examples/angular-published/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CourierInboxComponent, CourierService } from '@trycourier/courier-angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CourierInboxComponent],
  // Render Courier's default inbox, mirroring the default inbox in the
  // `angular` showcase.
  template: `<courier-inbox></courier-inbox>`,
})
export class AppComponent implements OnInit {
  constructor(private courier: CourierService) {}

  ngOnInit(): void {
    // Sign the user in so the inbox can load their messages. Without valid
    // credentials the inbox renders its empty / signed-out state.
    this.courier.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }
}
