// examples/react-latest/src/CustomListItems.tsx
import { useEffect } from 'react'
import {
  CourierInbox,
  useCourier,
  type CourierInboxListItemFactoryProps,
} from '@trycourier/courier-react';

const CustomListItem = ({ message, index }: CourierInboxListItemFactoryProps) => (
  <pre 
    onClick={() => alert(JSON.stringify({ message, index }, null, 2))}
    style={{
      padding: '24px',
      borderBottom: '1px solid #e0e0e0',
      margin: '0'
    }}>
    {JSON.stringify({ message, index }, null, 2)}
  </pre>
);

export default function App() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
      showLogs: false,
    });
  }, []);

  return (
    <CourierInbox
      renderListItem={(props: CourierInboxListItemFactoryProps | null | undefined) => {
        if (!props) return <></>;
        return <CustomListItem {...props} />;
      }}
    />
  );

}

// examples/angular/src/app/pages/custom-list-items.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  CourierInboxComponent,
  CourierService,
  type CourierInboxListItemFactoryProps,
} from '@trycourier/courier-angular';

@Component({
  selector: 'app-custom-list-items',
  standalone: true,
  imports: [CommonModule, CourierInboxComponent],
  template: `
    <courier-inbox>
      <ng-template #listItem let-props>
        <pre
          (click)="onClick(props)"
          style="padding: 24px; border-bottom: 1px solid #e0e0e0; margin: 0;"
        >{{ { message: props?.message, index: props?.index } | json }}</pre>
      </ng-template>
    </courier-inbox>
  `,
})
export class CustomListItemsComponent implements OnInit {
  constructor(private courier: CourierService) {}

  ngOnInit(): void {
    this.courier.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }

  onClick(props: CourierInboxListItemFactoryProps): void {
    alert(JSON.stringify({ message: props?.message, index: props?.index }, null, 2));
  }
}
