// examples/react-17/src/Home.tsx
import { useEffect } from 'react';
import { useCourier, CourierInbox } from '@trycourier/courier-react-17';
import { Link } from 'react-router-dom';

export default function Home() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }, []);

  const handleMessageClick = (props: any) => {
    alert(JSON.stringify(props, null, 2));
  };

  return (
    <div style={{ padding: '24px' }}>
      <div style={{ marginBottom: '24px' }}>
        <Link to="/examples" style={{ color: '#0066cc', textDecoration: 'underline' }}>
          View All Examples →
        </Link>
      </div>
      <CourierInbox onMessageClick={handleMessageClick} />
    </div>
  );

}

// examples/angular/src/app/pages/home.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import {
  CourierInboxComponent,
  CourierService,
  type CourierInboxListItemFactoryProps,
} from '@trycourier/courier-angular';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink, CourierInboxComponent],
  template: `
    <div style="padding: 24px;">
      <div style="margin-bottom: 24px;">
        <a routerLink="/examples" style="color: #0066cc; text-decoration: underline;">
          View All Examples →
        </a>
      </div>
      <courier-inbox (messageClick)="handleMessageClick($event)"></courier-inbox>
    </div>
  `,
})
export class HomeComponent implements OnInit {
  constructor(private courier: CourierService) {}

  ngOnInit(): void {
    this.courier.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }

  handleMessageClick(props: CourierInboxListItemFactoryProps): void {
    alert(JSON.stringify(props, null, 2));
  }
}
