// examples/react-17/src/PreferencesDefault.tsx
import { useEffect } from 'react';
import { CourierPreferences, useCourier } from '@trycourier/courier-react-17';

export default function PreferencesDefault() {
  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }, []);

  return (
    <div
      style={{
        margin: 0,
        minHeight: '100vh',
        background: '#F5F5F5',
        fontFamily:
          "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
      }}
    >
      <div style={{ padding: '40px 16px' }}>
        <CourierPreferences />
      </div>
    </div>
  );
}

// examples/angular/src/app/pages/preferences-default.component.ts
import { Component, OnInit } from '@angular/core';
import { CourierPreferencesComponent, CourierService } from '@trycourier/courier-angular';

@Component({
  selector: 'app-preferences-default',
  standalone: true,
  imports: [CourierPreferencesComponent],
  template: `
    <div
      style="margin: 0; min-height: 100vh; background: #F5F5F5;
             font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;"
    >
      <div style="padding: 40px 16px;">
        <courier-preferences></courier-preferences>
      </div>
    </div>
  `,
})
export class PreferencesDefaultComponent implements OnInit {
  constructor(private courier: CourierService) {}

  ngOnInit(): void {
    this.courier.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }
}
