// examples/angular/src/app/pages/custom-height.component.ts
import { Component, OnInit } from '@angular/core';
import { CourierInboxComponent, CourierService } from '@trycourier/courier-angular';

@Component({
  selector: 'app-custom-height',
  standalone: true,
  imports: [CourierInboxComponent],
  template: `
    <courier-inbox height="50vh"></courier-inbox>
  `,
})
export class CustomHeightComponent implements OnInit {
  constructor(private courier: CourierService) {}

  ngOnInit(): void {
    this.courier.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }
}

// examples/react-17/src/CustomHeight.tsx
import { useEffect } from 'react'
import { CourierInbox, useCourier } from '@trycourier/courier-react-17'

export default function App() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }, []);

  return <CourierInbox height='50vh' />;

}
