// examples/vue/src/Home.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useCourier, CourierInbox, type CourierInboxListItemFactoryProps } from '@trycourier/courier-vue';

const courier = useCourier();

onMounted(() => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
  });
});

const handleMessageClick = (props: CourierInboxListItemFactoryProps) => {
  alert(JSON.stringify(props, null, 2));
};
</script>

<template>
  <div :style="{ padding: '24px' }">
    <div :style="{ marginBottom: '24px' }">
      <router-link to="/examples" :style="{ color: '#0066cc', textDecoration: 'underline' }">
        View All Examples →
      </router-link>
    </div>
    <CourierInbox :on-message-click="handleMessageClick" />
  </div>
</template>

// examples/react-17/src/Home.tsx
import { useEffect } from 'react';
import { useCourier, CourierInbox } from '@trycourier/courier-react-17';
import { Link } from 'react-router-dom';

export default function Home() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
    });
  }, []);

  const handleMessageClick = (props: any) => {
    alert(JSON.stringify(props, null, 2));
  };

  return (
    <div style={{ padding: '24px' }}>
      <div style={{ marginBottom: '24px' }}>
        <Link to="/examples" style={{ color: '#0066cc', textDecoration: 'underline' }}>
          View All Examples →
        </Link>
      </div>
      <CourierInbox onMessageClick={handleMessageClick} />
    </div>
  );

}
