// examples/vue/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { Courier } from '@trycourier/courier-ui-inbox';

// A ref to the <courier-inbox> custom element so we can call its imperative API.
const inbox = ref<HTMLElement & {
  onMessageClick: (cb: (props: { message: unknown; index: number }) => void) => void;
} | null>(null);

onMounted(() => {
  Courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
  });

  inbox.value?.onMessageClick(({ message, index }) => {
    alert('Message clicked at index ' + index + ':\n' + JSON.stringify(message, null, 2));
  });
});
</script>

<template>
  <courier-inbox ref="inbox"></courier-inbox>
</template>

// examples/next-latest/src/app/page.tsx
'use client'

import { useEffect } from 'react';
import { useCourier, CourierInbox } from '@trycourier/courier-react';

export default function Home() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn({
      userId: process.env.NEXT_PUBLIC_USER_ID!,
      jwt: process.env.NEXT_PUBLIC_JWT!,
    });
  }, []);

  const handleMessageClick = (props: any) => {
    alert(JSON.stringify(props, null, 2));
  };

  return (
    <CourierInbox onMessageClick={handleMessageClick} />
  );

}
