// @trycourier/courier-react-components/src/components/courier-inbox-popup-menu-component.tsx
import { useEffect, useMemo, useRef, forwardRef, ReactNode, useContext, useState } from 'react';
import {
  CourierInboxHeaderFactoryProps,
  CourierInboxListItemActionFactoryProps,
  CourierInboxListItemFactoryProps,
  CourierInboxMenuButtonFactoryProps,
  CourierInboxPopupMenu as CourierInboxPopupMenuElement,
  CourierInboxPaginationItemFactoryProps,
  CourierInboxPopupAlignment,
  CourierInboxStateEmptyFactoryProps,
  CourierInboxStateErrorFactoryProps,
  CourierInboxStateLoadingFactoryProps,
  CourierInboxTheme,
  CourierInboxFeed,
} from '@trycourier/courier-ui-inbox';
import { CourierComponentThemeMode } from '@trycourier/courier-ui-core';
import { CourierClientComponent } from './courier-client-component';
import { CourierRenderContext } from '../context/render-context';

export interface CourierInboxPopupMenuProps {
  /** Alignment of the popup menu: 'top-right', 'top-left', 'top-center', 'bottom-right', 'bottom-left', 'bottom-center', 'center-right', 'center-left', 'center-center'. */
  popupAlignment?: CourierInboxPopupAlignment;

  /** Width of the popup menu container. */
  popupWidth?: string;

  /** Height of the popup menu container. */
  popupHeight?: string;

  /** CSS left position for the popup menu. */
  left?: string;

  /** CSS top position for the popup menu. */
  top?: string;

  /** CSS right position for the popup menu. */
  right?: string;

  /** CSS bottom position for the popup menu. */
  bottom?: string;

  /** Theme object for light mode. */
  lightTheme?: CourierInboxTheme;

  /** Theme object for dark mode. */
  darkTheme?: CourierInboxTheme;

  /** Theme mode: 'light', 'dark', or 'system'. */
  mode?: CourierComponentThemeMode;

  /** Array of feeds to display in the inbox. Each feed contains tabs with different filters. */
  feeds?: CourierInboxFeed[];

  /** Callback fired when a message is clicked. */
  onMessageClick?: (props: CourierInboxListItemFactoryProps) => void;

  /** Callback fired when a message action (e.g., button) is clicked. */
  onMessageActionClick?: (props: CourierInboxListItemActionFactoryProps) => void;

  /** Callback fired when a message is long-pressed (for mobile/gesture support). */
  onMessageLongPress?: (props: CourierInboxListItemFactoryProps) => void;

  /** Allows you to pass a custom component as the header. */
  renderHeader?: (props: CourierInboxHeaderFactoryProps | undefined | null) => ReactNode;

  /** Allows you to pass a custom component as the list item. */
  renderListItem?: (props: CourierInboxListItemFactoryProps | undefined | null) => ReactNode;

  /** Allows you to pass a custom component as the empty state. */
  renderEmptyState?: (props: CourierInboxStateEmptyFactoryProps | undefined | null) => ReactNode;

  /** Allows you to pass a custom component as the loading state. */
  renderLoadingState?: (props: CourierInboxStateLoadingFactoryProps | undefined | null) => ReactNode;

  /** Allows you to pass a custom component as the error state. */
  renderErrorState?: (props: CourierInboxStateErrorFactoryProps | undefined | null) => ReactNode;

  /** Allows you to pass a custom component as the pagination list item. */
  renderPaginationItem?: (props: CourierInboxPaginationItemFactoryProps | undefined | null) => ReactNode;

  /** Allows you to pass a custom component as the menu button. */
  renderMenuButton?: (props: CourierInboxMenuButtonFactoryProps | undefined | null) => ReactNode;
}

export const CourierInboxPopupMenuComponent = forwardRef<CourierInboxPopupMenuElement, CourierInboxPopupMenuProps>(
  (props, ref) => {
    const render = useContext(CourierRenderContext);
    if (!render) {
      throw new Error("RenderContext not found. Ensure CourierInboxPopupMenu is wrapped in a CourierRenderContext.");
    }

    // Element ref for use in effects, updated by handleRef.
    const inboxRef = useRef<CourierInboxPopupMenuElement | null>(null);
    const [elementReady, setElementReady] = useState(false);

    // Callback ref passed to rendered component, used to propagate the DOM element's ref to the parent component.
    // We use a callback ref (rather than a React.RefObject) since we want the parent ref to be up-to-date with
    // rendered component. Updating the parent ref via useEffect does not work, since mutating a RefObject
    // does not trigger useEffect (see https://stackoverflow.com/a/60476525).
    function handleRef(el: CourierInboxPopupMenuElement | null) {
      if (ref) {
        if (typeof ref === 'function') {
          ref(el);
        } else {
          // @ts-ignore - RefObject.current is readonly in React 17, however it's not frozen and is equivalent the widened type MutableRefObject
          (ref as React.RefObject<CourierInboxPopupMenuElement | null>).current = el;
        }
      }

      // Store the element for use in effects
      inboxRef.current = el;

      // Update element ready state
      setElementReady(!!el);
    }

    // Helper to get the current element
    function getEl(): CourierInboxPopupMenuElement | null {
      return inboxRef.current;
    }

    // Handle message click
    useEffect(() => {
      const menu = getEl();
      if (!menu) return;
      menu.onMessageClick(props.onMessageClick);
    }, [props.onMessageClick, elementReady]);

    // Handle message action click
    useEffect(() => {
      const menu = getEl();
      if (!menu) return;
      menu.onMessageActionClick(props.onMessageActionClick);
    }, [props.onMessageActionClick, elementReady]);

    // Handle message long press
    useEffect(() => {
      const menu = getEl();
      if (!menu) return;
      menu.onMessageLongPress(props.onMessageLongPress);
    }, [props.onMessageLongPress, elementReady]);

    // Render header
    useEffect(() => {
      const menu = getEl();
      if (!menu || !props.renderHeader) return;
      queueMicrotask(() => {
        menu.setHeader((headerProps?: CourierInboxHeaderFactoryProps | undefined | null): HTMLElement => {
          const reactNode = props.renderHeader!(headerProps);
          return render(reactNode);
        });
      });
    }, [props.renderHeader, elementReady]);

    // Render list item
    useEffect(() => {
      const menu = getEl();
      if (!menu || !props.renderListItem) return;
      queueMicrotask(() => {
        menu.setListItem((itemProps?: CourierInboxListItemFactoryProps | undefined | null): HTMLElement => {
          const reactNode = props.renderListItem!(itemProps);
          return render(reactNode);
        });
      });
    }, [props.renderListItem, elementReady]);

    // Render empty state
    useEffect(() => {
      const menu = getEl();
      if (!menu || !props.renderEmptyState) return;
      queueMicrotask(() => {
        menu.setEmptyState((emptyStateProps?: CourierInboxStateEmptyFactoryProps | undefined | null): HTMLElement => {
          const reactNode = props.renderEmptyState!(emptyStateProps);
          return render(reactNode);
        });
      });
    }, [props.renderEmptyState, elementReady]);

    // Render loading state
    useEffect(() => {
      const menu = getEl();
      if (!menu || !props.renderLoadingState) return;
      queueMicrotask(() => {
        menu.setLoadingState((loadingStateProps?: CourierInboxStateLoadingFactoryProps | undefined | null): HTMLElement => {
          const reactNode = props.renderLoadingState!(loadingStateProps);
          return render(reactNode);
        });
      });
    }, [props.renderLoadingState, elementReady]);

    // Render error state
    useEffect(() => {
      const menu = getEl();
      if (!menu || !props.renderErrorState) return;
      queueMicrotask(() => {
        menu.setErrorState((errorStateProps?: CourierInboxStateErrorFactoryProps | undefined | null): HTMLElement => {
          const reactNode = props.renderErrorState!(errorStateProps);
          return render(reactNode);
        });
      });
    }, [props.renderErrorState, elementReady]);

    // Render pagination item
    useEffect(() => {
      const menu = getEl();
      if (!menu || !props.renderPaginationItem) return;
      queueMicrotask(() => {
        menu.setPaginationItem((paginationProps?: CourierInboxPaginationItemFactoryProps | undefined | null): HTMLElement => {
          const reactNode = props.renderPaginationItem!(paginationProps);
          return render(reactNode);
        });
      });
    }, [props.renderPaginationItem, elementReady]);

    // Render menu button
    useEffect(() => {
      const menu = getEl();
      if (!menu || !props.renderMenuButton) return;
      queueMicrotask(() => {
        menu.setMenuButton((buttonProps?: CourierInboxMenuButtonFactoryProps | undefined | null): HTMLElement => {
          const reactNode = props.renderMenuButton!(buttonProps);
          return render(reactNode);
        });
      });
    }, [props.renderMenuButton, elementReady]);

    const feedsAttr = useMemo(
      () => props.feeds ? JSON.stringify(props.feeds) : undefined,
      [props.feeds]
    );

    const children = (
      /* @ts-ignore */
      <courier-inbox-popup-menu
        ref={handleRef}
        popup-alignment={props.popupAlignment}
        popup-width={props.popupWidth}
        popup-height={props.popupHeight}
        left={props.left}
        top={props.top}
        right={props.right}
        bottom={props.bottom}
        light-theme={props.lightTheme ? JSON.stringify(props.lightTheme) : undefined}
        dark-theme={props.darkTheme ? JSON.stringify(props.darkTheme) : undefined}
        mode={props.mode}
        feeds={feedsAttr as any}
      />
    );

    return (
      <CourierClientComponent children={children} />
    );
  }
);

// @trycourier/courier-angular/src/components/courier-inbox-popup-menu.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  EmbeddedViewRef,
  EventEmitter,
  inject,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  TemplateRef,
  ViewContainerRef,
} from "@angular/core";
import {
  CourierInboxPopupMenu as CourierInboxPopupMenuElement,
  type CourierInboxFeed,
  type CourierInboxHeaderFactoryProps,
  type CourierInboxListItemActionFactoryProps,
  type CourierInboxListItemFactoryProps,
  type CourierInboxMenuButtonFactoryProps,
  type CourierInboxPaginationItemFactoryProps,
  type CourierInboxPopupAlignment,
  type CourierInboxStateEmptyFactoryProps,
  type CourierInboxStateErrorFactoryProps,
  type CourierInboxStateLoadingFactoryProps,
  type CourierInboxTheme,
} from "@trycourier/courier-ui-inbox";
import type { CourierComponentThemeMode } from "@trycourier/courier-ui-core";
import { setAttr, setJsonAttr } from "../utils/attributes";
import { templateToHTMLElement } from "../utils/render-factory";

/**
 * CourierInboxPopupMenu Angular component — renders the inbox as a popup menu
 * anchored to a toggle button. The host element IS the
 * `<courier-inbox-popup-menu>` custom element.
 */
@Component({
  selector: "courier-inbox-popup-menu",
  standalone: true,
  template: "<ng-content></ng-content>",
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CourierInboxPopupMenuComponent implements AfterViewInit, OnChanges, OnDestroy {
  private readonly el = inject(ElementRef).nativeElement as CourierInboxPopupMenuElement;
  private readonly viewContainerRef = inject(ViewContainerRef);
  private readonly views: EmbeddedViewRef<unknown>[] = [];
  private ready = false;

  /** Alignment of the popup menu relative to its anchor. */
  @Input() popupAlignment?: CourierInboxPopupAlignment;
  /** Width of the popup menu container. */
  @Input() popupWidth?: string;
  /** Height of the popup menu container. */
  @Input() popupHeight?: string;
  /** CSS left position for the popup menu. */
  @Input() left?: string;
  /** CSS top position for the popup menu. */
  @Input() top?: string;
  /** CSS right position for the popup menu. */
  @Input() right?: string;
  /** CSS bottom position for the popup menu. */
  @Input() bottom?: string;
  /** Theme object for light mode. */
  @Input() lightTheme?: CourierInboxTheme;
  /** Theme object for dark mode. */
  @Input() darkTheme?: CourierInboxTheme;
  /** Theme mode: "light", "dark", or "system". */
  @Input() mode?: CourierComponentThemeMode;
  /** Array of feeds to display in the inbox. */
  @Input() feeds?: CourierInboxFeed[];

  /** Emits when a message is clicked. */
  @Output() messageClick = new EventEmitter<CourierInboxListItemFactoryProps>();
  /** Emits when a message action (e.g., button) is clicked. */
  @Output() messageActionClick = new EventEmitter<CourierInboxListItemActionFactoryProps>();
  /** Emits when a message is long-pressed. */
  @Output() messageLongPress = new EventEmitter<CourierInboxListItemFactoryProps>();

  /** `<ng-template #header>` rendered as a custom header. */
  @ContentChild("header", { read: TemplateRef }) headerTpl?: TemplateRef<unknown>;
  /** `<ng-template #listItem>` rendered as a custom list item. */
  @ContentChild("listItem", { read: TemplateRef }) listItemTpl?: TemplateRef<unknown>;
  /** `<ng-template #emptyState>` rendered as a custom empty state. */
  @ContentChild("emptyState", { read: TemplateRef }) emptyStateTpl?: TemplateRef<unknown>;
  /** `<ng-template #loadingState>` rendered as a custom loading state. */
  @ContentChild("loadingState", { read: TemplateRef }) loadingStateTpl?: TemplateRef<unknown>;
  /** `<ng-template #errorState>` rendered as a custom error state. */
  @ContentChild("errorState", { read: TemplateRef }) errorStateTpl?: TemplateRef<unknown>;
  /** `<ng-template #paginationItem>` rendered as a custom pagination list item. */
  @ContentChild("paginationItem", { read: TemplateRef }) paginationItemTpl?: TemplateRef<unknown>;
  /** `<ng-template #menuButton>` rendered as the menu toggle button. */
  @ContentChild("menuButton", { read: TemplateRef }) menuButtonTpl?: TemplateRef<unknown>;

  ngAfterViewInit(): void {
    this.ready = true;
    queueMicrotask(() => {
      this.syncAttributes();

      this.el.onMessageClick((props) => this.messageClick.emit(props));
      this.el.onMessageActionClick((props) => this.messageActionClick.emit(props));
      this.el.onMessageLongPress((props) => this.messageLongPress.emit(props));

      if (this.headerTpl) {
        this.el.setHeader((props: CourierInboxHeaderFactoryProps | undefined | null) =>
          this.renderTemplate(this.headerTpl!, props)
        );
      }
      if (this.listItemTpl) {
        this.el.setListItem((props: CourierInboxListItemFactoryProps | undefined | null) =>
          this.renderTemplate(this.listItemTpl!, props)
        );
      }
      if (this.emptyStateTpl) {
        this.el.setEmptyState((props: CourierInboxStateEmptyFactoryProps | undefined | null) =>
          this.renderTemplate(this.emptyStateTpl!, props)
        );
      }
      if (this.loadingStateTpl) {
        this.el.setLoadingState((props: CourierInboxStateLoadingFactoryProps | undefined | null) =>
          this.renderTemplate(this.loadingStateTpl!, props)
        );
      }
      if (this.errorStateTpl) {
        this.el.setErrorState((props: CourierInboxStateErrorFactoryProps | undefined | null) =>
          this.renderTemplate(this.errorStateTpl!, props)
        );
      }
      if (this.paginationItemTpl) {
        this.el.setPaginationItem((props: CourierInboxPaginationItemFactoryProps | undefined | null) =>
          this.renderTemplate(this.paginationItemTpl!, props)
        );
      }
      if (this.menuButtonTpl) {
        this.el.setMenuButton((props: CourierInboxMenuButtonFactoryProps | undefined | null) =>
          this.renderTemplate(this.menuButtonTpl!, props)
        );
      }
    });
  }

  ngOnChanges(): void {
    if (this.ready) {
      this.syncAttributes();
    }
  }

  private syncAttributes(): void {
    setAttr(this.el, "popup-alignment", this.popupAlignment);
    setAttr(this.el, "popup-width", this.popupWidth);
    setAttr(this.el, "popup-height", this.popupHeight);
    setAttr(this.el, "left", this.left);
    setAttr(this.el, "top", this.top);
    setAttr(this.el, "right", this.right);
    setAttr(this.el, "bottom", this.bottom);
    setJsonAttr(this.el, "light-theme", this.lightTheme);
    setJsonAttr(this.el, "dark-theme", this.darkTheme);
    setAttr(this.el, "mode", this.mode);
    setJsonAttr(this.el, "feeds", this.feeds);
  }

  private renderTemplate<P>(tpl: TemplateRef<unknown>, props: P): HTMLElement {
    const { element, view } = templateToHTMLElement(this.viewContainerRef, tpl, { $implicit: props, props });
    this.views.push(view);
    return element;
  }

  ngOnDestroy(): void {
    this.views.forEach((view) => view.destroy());
  }
}
