// @trycourier/courier-angular/src/components/courier-preferences.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  EventEmitter,
  inject,
  Input,
  OnChanges,
  Output,
} from "@angular/core";
import {
  CourierPreferences as CourierPreferencesElement,
  type CourierPreferencesTheme,
} from "@trycourier/courier-ui-preferences";
import type { CourierComponentThemeMode } from "@trycourier/courier-ui-core";
import { setAttr, setJsonAttr } from "../utils/attributes";

/**
 * CourierPreferences Angular component — renders the user's notification
 * preferences. The host element IS the `<courier-preferences>` custom element.
 */
@Component({
  selector: "courier-preferences",
  standalone: true,
  template: "<ng-content></ng-content>",
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CourierPreferencesComponent implements AfterViewInit, OnChanges {
  private readonly el = inject(ElementRef).nativeElement as CourierPreferencesElement;
  private ready = false;

  /** Theme object for light mode. */
  @Input() lightTheme?: CourierPreferencesTheme;
  /** Theme object for dark mode. */
  @Input() darkTheme?: CourierPreferencesTheme;
  /** Theme mode: "light", "dark", or "system". Defaults to "system". */
  @Input() mode?: CourierComponentThemeMode;
  /** Title displayed above the preferences. */
  @Input() title?: string;
  /** Subtitle displayed below the title. */
  @Input() subtitle?: string;
  /** Brand id used to theme the preferences. */
  @Input() brandId?: string;
  /** Map of channel keys to display labels. */
  @Input() channelLabels?: Record<string, string>;

  /** Emits when the component encounters an error. */
  @Output() error = new EventEmitter<Error>();

  ngAfterViewInit(): void {
    this.ready = true;
    queueMicrotask(() => this.syncAttributes());
  }

  ngOnChanges(): void {
    if (this.ready) {
      this.syncAttributes();
    }
  }

  private syncAttributes(): void {
    setJsonAttr(this.el, "light-theme", this.lightTheme);
    setJsonAttr(this.el, "dark-theme", this.darkTheme);
    setAttr(this.el, "title", this.title);
    setAttr(this.el, "subtitle", this.subtitle);
    setAttr(this.el, "brand-id", this.brandId);

    if (this.channelLabels) {
      this.el.setChannelLabels(this.channelLabels);
    }

    // When themes change, the web component's setDarkTheme/setLightTheme only
    // calls updateTheme() when _systemMode matches — it ignores an explicit
    // _userMode override. Re-calling setMode() always triggers updateTheme(),
    // picking up the new theme values.
    if (this.mode) {
      this.el.setMode(this.mode);
    } else {
      setAttr(this.el, "mode", this.mode);
    }
  }
}

// @trycourier/courier-react-components/src/components/courier-preferences-component.tsx
import { useRef, useEffect, forwardRef, CSSProperties } from "react";
import {
  CourierPreferencesTheme,
  CourierPreferences as CourierPreferencesElement,
} from "@trycourier/courier-ui-preferences";
import { CourierComponentThemeMode } from "@trycourier/courier-ui-core";
import { CourierClientComponent } from "./courier-client-component";

/** Props for the CourierPreferences React component. */
export interface CourierPreferencesProps {
  style?: CSSProperties;
  lightTheme?: CourierPreferencesTheme;
  darkTheme?: CourierPreferencesTheme;
  mode?: CourierComponentThemeMode;
  title?: string;
  subtitle?: string;
  brandId?: string;
  /** Render the draft (unpublished) preference page instead of the published one. */
  draft?: boolean;
  channelLabels?: Record<string, string>;
  onError?: (error: Error) => void;
}

export const CourierPreferencesComponent = forwardRef<CourierPreferencesElement, CourierPreferencesProps>((props, ref) => {
  const elRef = useRef<CourierPreferencesElement | null>(null);

  function handleRef(el: CourierPreferencesElement | null) {
    if (ref) {
      if (typeof ref === 'function') {
        ref(el);
      } else {
        // @ts-ignore
        (ref as React.RefObject<CourierPreferencesElement | null>).current = el;
      }
    }
    elRef.current = el;
  }

  useEffect(() => {
    const el = elRef.current;
    if (!el) return;
    if (props.channelLabels) {
      el.setChannelLabels(props.channelLabels);
    }
  }, [props.channelLabels]);

  // When themes change, the web component's setDarkTheme/setLightTheme only calls
  // updateTheme() when _systemMode matches — it ignores an explicit _userMode override.
  // Re-calling setMode() always triggers updateTheme(), picking up the new theme values.
  useEffect(() => {
    const el = elRef.current;
    if (!el || !props.mode) return;
    el.setMode(props.mode);
  }, [props.lightTheme, props.darkTheme, props.mode]);

  const children = (
    /* @ts-ignore */
    <courier-preferences
      ref={handleRef}
      style={props.style}
      light-theme={props.lightTheme ? JSON.stringify(props.lightTheme) : undefined}
      dark-theme={props.darkTheme ? JSON.stringify(props.darkTheme) : undefined}
      mode={props.mode}
      title={props.title}
      subtitle={props.subtitle}
      brand-id={props.brandId}
      draft={props.draft ? "true" : undefined}
    />
  );

  return (
    <CourierClientComponent children={children} />
  );
});

CourierPreferencesComponent.displayName = 'CourierPreferencesComponent';
