// examples/vue/src/ElementRef.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { CourierInbox, useCourier, type CourierInboxElement } from '@trycourier/courier-vue';

const courier = useCourier();
const inboxComp = ref<{ getElement: () => CourierInboxElement | null } | null>(null);

onMounted(() => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
    showLogs: false,
  });

  // Access the underlying inbox web component element via the exposed getElement().
  inboxComp.value?.getElement()?.removeHeader();
});
</script>

<template>
  <CourierInbox ref="inboxComp" />
</template>

// examples/react-latest/src/ElementRef.tsx
import { useEffect, useRef } from 'react'
import { CourierInbox, useCourier } from '@trycourier/courier-react'
import { CourierInbox as CourierInboxElement } from '@trycourier/courier-ui-inbox'

export default function App() {

  const courier = useCourier();
  const inboxRef = useRef<CourierInboxElement>(null);

  useEffect(() => {
    courier.shared.signIn({
      userId: import.meta.env.VITE_USER_ID,
      jwt: import.meta.env.VITE_JWT,
      showLogs: false,
    });
  }, []);
  useEffect(() => {
    if (inboxRef.current) {
      inboxRef.current.removeHeader();
    }
  }, [inboxRef.current]);

  return <CourierInbox ref={inboxRef} />;

}
