// examples/vue/src/InboxPopupMenuDefault.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { CourierInboxPopupMenu, useCourier } from '@trycourier/courier-vue';

const courier = useCourier();

onMounted(() => {
  courier.shared.signIn({
    userId: import.meta.env.VITE_USER_ID,
    jwt: import.meta.env.VITE_JWT,
    showLogs: false,
  });
});
</script>

<template>
  <div :style="{ padding: '24px' }">
    <CourierInboxPopupMenu />
  </div>
</template>

// examples/react-latest/src/InboxPopupMenuDefault.tsx
import { useEffect } from 'react'
import { CourierInboxPopupMenu, useCourier } from '@trycourier/courier-react'
import { getSignInProps } from './courier-env'

export default function App() {

  const courier = useCourier();

  useEffect(() => {
    courier.shared.signIn(getSignInProps({ showLogs: false }));
  }, []);

  return (
    <div style={{ padding: '24px' }}>
      <CourierInboxPopupMenu />
    </div>
  );

}
